spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared2
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD:password}

server:
  port: 8888

