spring:
  application:
    name: notification-service
  cloud:
    config:
      #uri: http://config:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  config:
    import: optional:configserver:http://127.0.0.1:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:5000/uaa