spring:
  application:
    name: registry
  cloud:
    config:
      #uri: http://config:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD:password}
      username: user
  config:
    import: optional:configserver:http://10.100.53.106:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0