server:
  servlet:
    context-path: /accounts
  port: 6000

spring:
  data:
    mongodb:
      host: 127.0.0.1 #account-mongodb
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27017
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      oauth2:
        enabled: true
        clientRegistrationId: account-service-client-credentials
      httpclient:
        connection-timeout: 600000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.53.106:5000/uaa
      client:
        registration:
          account-service-client-credentials:
            provider: spring
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD:password1}
            authorization-grant-type: client_credentials
            scope: server
            client-name: account-service-client-credentials
        provider:
          spring:
            issuer-uri: http://10.100.53.106:5000/uaa

#security:
#  oauth2:
#    client:
#      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

#feign:
#  hystrix:
#    enabled: true