logging:
  level:
    org.springframework.security: DEBUG
    #Gateway
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    reactor.netty: DEBUG
    redisratelimiter: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.100.53.106:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://10.100.53.106:5000/uaa/users/current

spring:
  rabbitmq:
    host: 10.100.53.131