server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.53.106:5000/uaa
