server:
  port: 80

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:5000
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:

    statistics-service:
      path: /statistics/**
      serviceId: statistics-service
      stripPrefix: false
      sensitiveHeaders:

    notification-service:
      path: /notifications/**
      serviceId: notification-service
      stripPrefix: false
      sensitiveHeaders:

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service:5000
          predicates:
            - Path=/uaa/**
        - id: account-service
          uri: lb://account-service:6000
          predicates:
            - Path=/accounts/**
        - id: statistics-service
          uri: lb://statistics-service:7000
          predicates:
            - Path=/statistics/**
        - id: notification-service
          uri: lb://notification-service:8000
          predicates:
            - Path=/notifications/**


