server:
  servlet:
    context-path: /notifications
  port: 8000

remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! We''ve missed you here on PiggyMetrics. It''s time to check your budget statistics.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics reminder

backup:
  cron: 0 0 12 * * *
  email:
    text: "Howdy, {0}. Your account backup is ready.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics account backup
    attachment: backup.json

spring:
  data:
    mongodb:
      host: 127.0.0.1 #notification-mongodb
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      oauth2:
        enabled: true
        clientRegistrationId: notification-service-client-credentials
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.53.106:5000/uaa
      client:
        registration:
          notification-service-client-credentials:
            provider: spring
            client-id: notification-service
            client-secret: ${NOTIFICATION_SERVICE_PASSWORD:password3}
            authorization-grant-type: client_credentials
            scope: server
            client-name: notification-service-client-credentials
        provider:
          spring:
            issuer-uri: http://10.100.53.106:5000/uaa
