server:
  servlet:
    context-path: /statistics
  port: 7000

spring:
  data:
    mongodb:
      host: 127.0.0.1 #statistics-mongodb
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27017
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      oauth2:
        enabled: true
        clientRegistrationId: statistics-service-client-credentials
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:5000/uaa
      client:
        registration:
          statistics-service-client-credentials:
            provider: spring
            client-id: statistics-service
            client-secret: ${STATISTICS_SERVICE_PASSWORD:password2}
            authorization-grant-type: client_credentials
            scope: server
            client-name: statistics-service-client-credentials
        provider:
          spring:
            issuer-uri: http://127.0.0.1:5000/uaa

#security:
#  oauth2:
#    client:
#      clientId: statistics-service
#      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server



rates:
  url: https://abc.dummy.com # https://api.exchangeratesapi.io