spring:
                  application:
  name: account-service
  cloud:
    config:
      #uri: http://config:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user

    openfeign:
      circuitbreaker:
        enabled: true
      oauth2:
        enabled: true


  config:
    import: optional:configserver:http://127.0.0.1:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:5000/uaa

